server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 valid=10s;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /mf/bookings/ {
        alias /usr/share/nginx/html/mf/bookings/;
    }
    location /mf/meetings/ {
        alias /usr/share/nginx/html/mf/meetings/;
    }
    location /mf/admin/ {
        alias /usr/share/nginx/html/mf/admin/;
    }

    location /api/auth {
        proxy_pass http://auth-service:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/rooms {
        proxy_pass http://rooms-service:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/bookings {
        proxy_pass http://bookings-service:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/invitations {
        proxy_pass http://invitations-service:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
